name: Publish

on:
  push:
    tags: [v*]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          tags: unodocsl/unoserver:${{ steps.package-version.outputs.current-version }},unodocsl/unoserver:latest
          build-args: NODE_ENV=production
          push: true
      - uses: docker/build-push-action@v6
        with:
          tags: unodocsl/unoserver:${{ steps.package-version.outputs.current-version }}-fonts,unodocsl/unoserver:latest-fonts
          build-args: |
            NODE_ENV=production
            GOOGLE_FONTS=1
          push: true
